BEGIN TRANSACTION;
CREATE TABLE "symbol" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`code`	TEXT NOT NULL UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
INSERT INTO `symbol` VALUES (1,'BTC','Bitcoin'),
 (2,'LTC','Litecoin'),
 (3,'DOGE','Dogecoin');
COMMIT;
